# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Giris.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Giris(object):
    def setupUi(self, Giris):
        Giris.setObjectName("Giris")
        Giris.resize(299, 360)
        self.centralwidget = QtWidgets.QWidget(Giris)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 281, 71))
        self.label.setObjectName("label")
        self.btn200 = QtWidgets.QPushButton(self.centralwidget)
        self.btn200.setGeometry(QtCore.QRect(80, 70, 141, 51))
        self.btn200.setObjectName("btn200")
        self.btn201 = QtWidgets.QPushButton(self.centralwidget)
        self.btn201.setGeometry(QtCore.QRect(80, 130, 141, 51))
        self.btn201.setObjectName("btn201")
        self.btn202 = QtWidgets.QPushButton(self.centralwidget)
        self.btn202.setGeometry(QtCore.QRect(80, 190, 141, 51))
        self.btn202.setObjectName("btn202")
        self.btn203 = QtWidgets.QPushButton(self.centralwidget)
        self.btn203.setGeometry(QtCore.QRect(80, 250, 141, 51))
        self.btn203.setObjectName("btn203")
        Giris.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Giris)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 299, 21))
        self.menubar.setObjectName("menubar")
        Giris.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Giris)
        self.statusbar.setObjectName("statusbar")
        Giris.setStatusBar(self.statusbar)

        self.retranslateUi(Giris)
        QtCore.QMetaObject.connectSlotsByName(Giris)

    def retranslateUi(self, Giris):
        _translate = QtCore.QCoreApplication.translate
        Giris.setWindowTitle(_translate("Giris", "MainWindow"))
        self.label.setText(_translate("Giris", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">STOK TAKİP PROGRAMINA</span></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">HOŞGELDİNİZ</span></p></body></html>"))
        self.btn200.setText(_translate("Giris", "Kayıt Ekle"))
        self.btn201.setText(_translate("Giris", "Geçmiş"))
        self.btn202.setText(_translate("Giris", "-----"))
        self.btn203.setText(_translate("Giris", "------"))
